import { test, expect } from '@playwright/test';

const base = process.env.BASE_URL || 'http://127.0.0.1:3000';
test('desktop: generate, refine, favorite, history and delete', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1080 });
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(base);
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Ваша идея.');
  await page.waitForLoadState('networkidle');
  await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Создать промпт', exact: true }).click();
  await expect(page.locator('.error-message')).toContainText('Опишите вашу идею');
  await page.getByRole('textbox', { name: 'Ваша идея' }).fill('Составь план продвижения небольшой кофейни');
  await page.getByRole('button', { name: 'Создать промпт', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Идея обрела форму.' })).toBeVisible();
  await expect(page.locator('.prompt-output')).toContainText('кофейни');
  await expect(page.locator('.demo-note')).toBeVisible();
  await page.getByRole('button', { name: 'В избранное', exact: true }).click();
  await expect(page.getByRole('button', { name: 'В избранное', exact: true })).toHaveClass(/is-favorite/);
  await page.getByRole('button', { name: 'Доработать', exact: true }).click();
  await page.getByRole('textbox', { name: 'Ваша идея' }).fill('Добавь контент-план на неделю');
  await page.getByRole('button', { name: 'Доработать промпт', exact: true }).click();
  await expect(page.locator('.prompt-output')).toContainText('Previous draft to revise');
  await expect(page.locator('.prompt-output')).toContainText('кофейни');
  await page.getByRole('button', { name: 'История промптов', exact: true }).click();
  await expect(page.locator('.history-list article')).toHaveCount(2);
  await page.getByRole('textbox', { name: 'Поиск по истории' }).fill('небывалыйпоиск');
  await expect(page.getByRole('heading', { name: 'Ничего не найдено' })).toBeVisible();
  await page.getByRole('button', { name: 'Сбросить поиск' }).click();
  await expect(page.locator('.history-list article')).toHaveCount(2);
  page.on('dialog', d => d.accept());
  await page.getByRole('button', { name: 'Удалить промпт', exact: true }).first().click();
  await expect(page.locator('.history-list article')).toHaveCount(1);
  await page.getByRole('button', { name: 'Удалить промпт', exact: true }).first().click();
  await expect(page.getByRole('heading', { name: 'Всё начинается с одной идеи' })).toBeVisible();
  expect(errors).toEqual([]);
});

test('iPhone layout, settings, image parameters and reference safeguards', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 402, height: 874 }, deviceScaleFactor: 3, isMobile: true, hasTouch: true });
  const page = await context.newPage();
  await page.goto(base);
  await page.waitForLoadState('networkidle');
  await page.screenshot({ path: 'artifacts/iphone.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('banner').getByRole('button', { name: 'Подключение ИИ', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('dialog')).toContainText('GitHub Pages');
  await page.getByRole('button', { name: 'Понятно' }).click();
  await expect(page.locator('.model-select strong')).toContainText('Локальный шаблон');
  await page.getByRole('tab', { name: 'Для изображения', exact: true }).click();
  await page.getByRole('button', { name: '9:16', exact: true }).click();
  await page.getByLabel('Визуальный стиль').selectOption('Аниме');
  await page.getByRole('textbox', { name: 'Ваша идея' }).fill('Кот на крыше под звёздным небом');
  await page.getByRole('button', { name: 'Создать промпт', exact: true }).click();
  await expect(page.locator('.prompt-output')).toContainText('9:16');
  await expect(page.locator('.prompt-output')).toContainText('Аниме');
  await page.getByRole('tab', { name: 'По референсу' }).click();
  await page.locator('input[type=file]').setInputFiles('public/icons/icon-512.png');
  await expect(page.getByAltText('Загруженный референс')).toBeVisible();
  await page.getByRole('button', { name: 'Создать промпт', exact: true }).click();
  await expect(page.locator('.error-message')).toContainText('безопасного API‑сервера');
  await page.getByRole('button', { name: 'Открыть меню' }).click();
  await page.getByRole('button', { name: 'Установить приложение', exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText('Safari');
  await page.getByRole('button', { name: 'Всё понятно' }).click();
  await page.getByRole('button', { name: 'История промптов', exact: true }).click();
  await expect(page.locator('.history-list article')).toHaveCount(1);
  await page.waitForFunction(() => localStorage.getItem('forma_offline_ready') === '1');
  await context.setOffline(true);
  await page.reload();
  await page.getByRole('button', { name: 'Открыть меню' }).click();
  await page.getByRole('button', { name: 'История промптов', exact: true }).click();
  await expect(page.locator('.history-list article')).toHaveCount(1);
  await context.setOffline(false);
  page.on('dialog', d => d.accept());
  await page.getByRole('button', { name: 'Удалить промпт', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Всё начинается с одной идеи' })).toBeVisible();
  await context.close();
});
